[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/focus"
  to = "/focus.html"
  status = 200

[[redirects]]
  from = "/checklist"
  to = "/checklist.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/src/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
